# Site settings
title: David Pazdera
twitter_username: pazdedav
name: David Pazdera

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://dev.to/pazdedav
 - title: GitHub
   url: https://github.com/pazdedav
 - title: LinkedIn
   url: https://no.linkedin.com/in/pazdedav
 - title: Sessionize
   url: https://sessionize.com/david-pazdera/

#Any buzzword skills you want to include
skills:
 - solution design
 - cloud infrastructure (Azure)
 - cloud governance (Azure)
 - DevOps (using Azure DevOps or GitHub)
 - automation with PowerShell
 - infrastructure as code (ARM JSON, Bicep)

#Work experience is required
roles:
 - title: Cloud Solution Architect
   start: 2016
   end: Ongoing
   employer: Microsoft Norway
   description: Technical, customer facing role that accountable for the end-to-end customer cloud deployment experience.
 - title: (Lead) Solution Architect
   start: 2011
   end: 2016
   employer: Tieto Norway
   description: Working on large infrastructure & application outsourcing bids, responsible for solution architecture; supporting transition and transformation projects.
 - title: Lead Technical Specialist
   start: 2009
   end: 2011
   employer: Tieto Czech republic
   description: Technical support in messaging and collaboration area (MS Exchange 2003/2007, OCS 2007) with competence in dependant areas (Active Directory, Network infrastructure); M&C Projects; Problem management.
 - title: System administrator
   start: 2004
   end: 2006
   employer: Darkov Spa, Inc.
   description: Design of system infrastructure (AD, DNS, DHCP, VLAN); Windows server administration (Windows 2000/2003); ERP implementation; Network security (VPN, RAS); Messaging services migration.

#Education is required
education:
 - level: Master of Science (M.Sc.)
   date: 2002
   subject: Managerial informatics
   school: Silesian University, School of Business Administration, Karvina (Czech Republic)

#List of interesting Github repo/projects to include - optional
github:
 - pazdedav/azure-image-factory
 - pazdedav/ad-join
 - pazdedav/eslz-adoproject-template

intro: |
  I am a cloud engineer and architect with 20 years experience working in technology. I have primarily worked as an IT Pro with network, Windows Server platform, Active Directory, Unified Communications (Exchange, Lync). <br/><br/>
  In more recent past, I worked with large tenders / IT outsourcing bids in Norway, where my role was to design and describe a solution matching all customer's requirements. <br/><br/>
  Currently, I am focusing on Azure infrastructure, automation, DevOps, and "everything as Code" principle.
 
